"""Encode the unchanged original JSON certificate as exact Lean natural literals."""
import json
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "verification" / "certificate.json"
EXPECTED_SHA = "8384d62a377b4fcac4080d0e05979d7a6fcf90437b7e4911927a5403d4052709"
raw = SOURCE.read_bytes()
assert hashlib.sha256(raw).hexdigest() == EXPECTED_SHA
doc = json.loads(raw)
assert (doc['precision_bits'], doc['m_start'], doc['m_stop_exclusive']) == (100, 5, 1000000)
rows = doc['records']
assert len(rows) == 6593
tags = {'direct':0, 'center-monotone':1, 'center-cubic':2, 'boundary':3}
groups = []
for index, row in enumerate(rows):
    ml,mh,al,ah,h,tag,sub = row
    if not groups or groups[-1][0] != (ml,mh):
        groups.append(((ml,mh), []))
    groups[-1][1].append(index)

out = ROOT / 'QuadraticTangZhang' / 'Certificate'
out.mkdir(exist_ok=True)
lines = ['import QuadraticTangZhang.CertificateMesh', '',
         '/-! Exact encoding of all 6593 original records. Generated by verification/encode_certificate.py. -/',
         'set_option maxRecDepth 100000', 'namespace QuadraticTangZhang.CertificateData', '']
for i,row in enumerate(rows):
    ml,mh,al,ah,h,tag,sub=row
    lines.append(f'def record_{i:04d} : CertificateRecord := decodeRecord {ml} {mh} {al} {ah} {h} {tags[tag]} {sub}')
for j,((ml,mh),indices) in enumerate(groups):
    refs=', '.join(f'record_{i:04d}' for i in indices)
    lines.append(f'def block_{j:03d} : DegreeBlock := ⟨{ml},{mh},[{refs}]⟩')
lines.extend(['', 'def blocks : List DegreeBlock := [', ',\n'.join(f'  block_{i:03d}' for i in range(len(groups))),']',
              '', 'def records : List CertificateRecord := blocks.flatMap DegreeBlock.records',
              '', 'end QuadraticTangZhang.CertificateData', ''])
(out/'Data.lean').write_text('\n'.join(lines),encoding='utf-8')
print(json.dumps({'records':len(rows),'blocks':len(groups),'sha256':EXPECTED_SHA}))
